"""Unit tests. Run with: python -m pytest tests -q"""
import sys, os
import numpy as np
import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from dissokin.models import MODELS, MODELS_BY_NAME, peppas_mechanism
from dissokin.fitting import (fit_model, fit_all, bootstrap_params,
                              fit_kp_loglog, first_60_percent)
from dissokin.similarity import f1_difference, f2_similarity, f2_with_uncertainty
from dissokin.simulate import GRIDS, SCENARIOS, simulate_profile, truth_curve

T = np.array(GRIDS["log10"].times, dtype=float)


@pytest.mark.parametrize("m", MODELS, ids=[m.name for m in MODELS])
def test_models_are_monotone_and_bounded(m):
    """Every release model must be non decreasing and stay within 0 to 100."""
    p0 = np.array(m.p0, dtype=float)
    y = np.asarray(m.func(T, *p0), dtype=float)
    assert y.shape == T.shape
    assert np.all(np.isfinite(y))
    assert np.all(np.diff(y) >= -1e-9), "release must not go backwards"
    assert y.min() >= -1e-9
    assert y.max() <= 100.0 + 1e-6


def test_zero_time_gives_zero_release():
    for m in MODELS:
        if m.name == "Korsmeyer-Peppas":
            continue  # power law is singular at t = 0 for n < 1
        y = float(np.atleast_1d(m.func(np.array([1e-12]), *m.p0))[0])
        assert abs(y) < 1e-3, f"{m.name} released {y} at t = 0"


def test_baker_lonsdale_inverts_its_own_equation():
    """The bisection solution must satisfy the implicit Baker-Lonsdale form."""
    k = 0.03
    q = MODELS_BY_NAME["Baker-Lonsdale"].func(T, k) / 100.0
    lhs = 1.5 * (1.0 - (1.0 - q) ** (2.0 / 3.0)) - q
    assert np.allclose(lhs, k * T, atol=1e-6)


def test_higuchi_recovered_from_noiseless_data():
    q = truth_curve("Higuchi", (26.0,), T)
    fr = fit_model(T, q, MODELS_BY_NAME["Higuchi"])
    assert fr.converged
    assert abs(fr.params["kH"] - 26.0) < 1e-3
    assert fr.r2 > 0.999999


def test_peppas_parameters_recovered_within_bootstrap_interval():
    rng = np.random.default_rng(7)
    q = simulate_profile("Korsmeyer-Peppas", (28.0, 0.42), T, 2.0, rng)
    kp = MODELS_BY_NAME["Korsmeyer-Peppas"]
    ci = bootstrap_params(T, q, kp, n_boot=300, seed=7)
    assert ci["n"]["ci_low"] <= 0.42 <= ci["n"]["ci_high"]


def test_aicc_penalises_the_extra_parameter():
    """On data generated by a one parameter law, the two parameter model can
    never have a worse fit, but must be penalised by AICc."""
    q = truth_curve("Higuchi", (26.0,), T) + np.random.default_rng(1).normal(0, 2, T.size)
    res = {r.model: r for r in fit_all(T, q)}
    hig, kp = res["Higuchi"], res["Korsmeyer-Peppas"]
    assert kp.rss <= hig.rss + 1e-8, "nested richer model cannot fit worse"
    assert kp.aicc > hig.aicc - 1e-9 or kp.rss < hig.rss * 0.9


def test_akaike_weights_sum_to_one():
    rng = np.random.default_rng(3)
    q = simulate_profile("Weibull", (6.0, 0.85), T, 2.0, rng)
    res = fit_all(T, q)
    w = sum(r.akaike_weight for r in res if np.isfinite(r.akaike_weight))
    assert abs(w - 1.0) < 1e-9


def test_mechanism_boundaries_match_ritger_peppas():
    assert peppas_mechanism(0.30) == "Quasi-Fickian diffusion"
    assert peppas_mechanism(0.45) == "Anomalous (non-Fickian) transport"
    assert peppas_mechanism(0.60) == "Anomalous (non-Fickian) transport"
    assert peppas_mechanism(0.89) == "Case II transport (zero order)"
    assert peppas_mechanism(1.10) == "Super Case II transport"
    # sphere boundaries are lower than slab boundaries
    assert peppas_mechanism(0.44, "sphere") == "Anomalous (non-Fickian) transport"
    assert peppas_mechanism(0.44, "slab") == "Quasi-Fickian diffusion"


def test_sixty_percent_rule_keeps_only_the_leading_run():
    t = np.array([1.0, 2, 3, 4, 5])
    q = np.array([20.0, 45, 61, 58, 80])   # 58 dips back below the cutoff
    tk, qk = first_60_percent(t, q)
    assert tk.tolist() == [1.0, 2.0]
    assert qk.tolist() == [20.0, 45.0]


def test_loglog_and_nonlinear_agree_on_noiseless_data():
    q = truth_curve("Korsmeyer-Peppas", (28.0, 0.42), T)
    lin = fit_kp_loglog(T, q)
    nls = fit_model(T, q, MODELS_BY_NAME["Korsmeyer-Peppas"])
    assert abs(lin["n"] - 0.42) < 1e-6
    assert abs(nls.params["n"] - 0.42) < 1e-4


def test_f2_of_identical_profiles_is_one_hundred():
    ref = np.array([20.0, 40, 60, 80, 90])
    assert abs(f2_similarity(ref, ref) - 100.0) < 1e-9
    assert f1_difference(ref, ref) == 0.0


def test_f2_falls_below_fifty_for_a_ten_percent_offset():
    ref = np.array([20.0, 40, 60, 80, 90])
    assert f2_similarity(ref, ref + 11.0) < 50.0
    assert f2_similarity(ref, ref + 4.0) > 50.0


def test_f2_bootstrap_interval_contains_the_point_estimate():
    rng = np.random.default_rng(11)
    base = np.array([20.0, 40, 60, 80, 90])
    R = base + rng.normal(0, 3, (12, 5))
    Tst = base + 4.0 + rng.normal(0, 3, (12, 5))
    out = f2_with_uncertainty(R, Tst, n_boot=800, seed=11)
    assert out["ci_low"] <= out["f2"] <= out["ci_high"]
    assert 0.0 <= out["p_below_50"] <= 1.0


def test_simulated_profiles_stay_in_range():
    rng = np.random.default_rng(5)
    for name, (m, p) in SCENARIOS.items():
        q = simulate_profile(m, p, T, 5.0, rng)
        assert q.min() >= 0.0 and q.max() <= 100.0, name
