"""Emit paper/numbers.tex so that every figure quoted in the report is taken
straight from the stored results and cannot drift out of date."""
from __future__ import annotations
import sys, os, json
import numpy as np
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from dissokin.models import MODELS_BY_NAME

RES = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "paper", "numbers.tex")
lines = []


def cmd(name, value):
    lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")


def _write_table(path, header_tex, rows, caption, label, colspec):
    """Write a complete table environment.

    The body cannot be \\input inside a tabular: LaTeX's \\input opens a
    group that TeX's alignment scanner rejects, so \\bottomrule then lands
    inside a half started row. Emitting the whole float sidesteps it.
    """
    body = "\n".join(rows)
    with open(path, "w") as fh:
        fh.write("% generated by examples/make_report_numbers.py\n")
        fh.write("\\begin{table}[t]\n\\centering\n\\small\n")
        fh.write(f"\\caption{{{caption}}}\n\\label{{{label}}}\n")
        fh.write(f"\\begin{{tabular}}{{{colspec}}}\n\\toprule\n")
        fh.write(header_tex + "\n\\midrule\n")
        fh.write(body + "\n\\bottomrule\n")
        fh.write("\\end{tabular}\n\\end{table}\n")


def pct(x, d=0):
    return f"{100*x:.{d}f}\\%"


# ------------------------------------------------------------ experiment 1
S = json.load(open(os.path.join(RES, "selection_study.json")))
R = S["rows"]
cmd("selNrep", S["n_rep"])
cmd("selNcond", len(R))
cmd("selNprof", f"{len(R)*S['n_rep']:,}".replace(",", "\\,"))
for key, nm in [("recovery_r2", "RecRtwo"), ("recovery_r2_adj", "RecAdj"),
                ("recovery_aicc", "RecAICc"), ("recovery_bic", "RecBIC")]:
    cmd(nm, pct(np.mean([r[key] for r in R])))
cmd("Disagree", pct(np.mean([r["disagree_r2_aicc"] for r in R])))
cmd("MeanBestRtwo", f"{np.mean([r['mean_r2_best'] for r in R]):.4f}")
gaps = [r["mean_r2_gap"] for r in R if np.isfinite(r["mean_r2_gap"])]
cmd("GapMedian", f"{np.median(gaps):.5f}")
cmd("GapNinety", f"{np.percentile(gaps, 90):.4f}")
cmd("NparRtwo", f"{np.mean([r['mean_npar_r2'] for r in R]):.2f}")
cmd("NparAICc", f"{np.mean([r['mean_npar_aicc'] for r in R]):.2f}")

one_par = [r for r in R if MODELS_BY_NAME[r["truth"]].k == 1]
two_par = [r for r in R if MODELS_BY_NAME[r["truth"]].k == 2]
cmd("RecRtwoOnePar", pct(np.mean([r["recovery_r2"] for r in one_par]), 1))
cmd("RecAICcOnePar", pct(np.mean([r["recovery_aicc"] for r in one_par])))
cmd("RecRtwoTwoPar", pct(np.mean([r["recovery_r2"] for r in two_par])))
cmd("RecAICcTwoPar", pct(np.mean([r["recovery_aicc"] for r in two_par])))
cmd("NOnePar", f"{len(one_par) * S['n_rep']:,}".replace(",", "\\,"))

def top_pick(truth, field):
    c = Counter()
    for r in R:
        if r["truth"] == truth:
            c.update(r[field])
    tot = sum(c.values())
    m, n = c.most_common(1)[0]
    return m, n / tot

m, f = top_pick("Higuchi", "picks_r2");  cmd("HigPickRtwo", m); cmd("HigPickRtwoF", pct(f))
m, f = top_pick("Higuchi", "picks_aicc"); cmd("HigPickAICcF", pct(f))
m, f = top_pick("First order", "picks_r2"); cmd("FoPickRtwo", m); cmd("FoPickRtwoF", pct(f))
m, f = top_pick("Korsmeyer-Peppas", "picks_aicc")
cmd("KPPickAICc", m); cmd("KPPickAICcF", pct(f))
cmd("KPRecAICc", pct(np.mean([r["recovery_aicc"] for r in R
                              if r["truth"] == "Korsmeyer-Peppas"])))
cmd("KPRecRtwo", pct(np.mean([r["recovery_r2"] for r in R
                              if r["truth"] == "Korsmeyer-Peppas"])))
lo = [r for r in R if r["sigma"] == 1.0]
hi = [r for r in R if r["sigma"] == 5.0]
cmd("RecAICcLowNoise", pct(np.mean([r["recovery_aicc"] for r in lo])))
cmd("RecAICcHighNoise", pct(np.mean([r["recovery_aicc"] for r in hi])))
six = [r for r in R if r["n_points"] == 6]
sixteen = [r for r in R if r["n_points"] == 16]
cmd("RecAICcSix", pct(np.mean([r["recovery_aicc"] for r in six])))
cmd("RecAICcSixteen", pct(np.mean([r["recovery_aicc"] for r in sixteen])))

# per truth table
rows = []
for tn in sorted({r["truth"] for r in R}):
    s = [r for r in R if r["truth"] == tn]
    rows.append(f"{tn} & {MODELS_BY_NAME[tn].k} & "
                + " & ".join(f"{100*np.mean([r[k] for r in s]):.1f}"
                             for k in ("recovery_r2", "recovery_r2_adj",
                                       "recovery_aicc", "recovery_bic")) + r" \\")
_write_table(
    os.path.join(ROOT, "paper", "table_selection.tex"),
    r"Generating model & $k$ & $R^2$ & adj. $R^2$ & AICc & BIC \\",
    rows,
    "Percentage of profiles in which each rule recovered the generating "
    "model, by truth. $k$ is the number of free parameters in the true "
    f"model. Pooled over schedules and noise levels, {S['n_rep']} "
    "replicates per condition.",
    "tab:selection", "lcrrrr")

# ------------------------------------------------------------ experiment 2
M = json.load(open(os.path.join(RES, "mechanism_study.json")))
Rm = M["rows"]
cmd("mechNrep", M["n_rep"]); cmd("mechNboot", M["n_boot"])
cmd("mechNcond", len(Rm))
cmd("mechKept", f"{np.mean([r['mean_points_kept'] for r in Rm]):.1f}")
cmd("mechKeptMin", f"{min(r['mean_points_kept'] for r in Rm):.1f}")
cmd("BiasNLS", f"{np.mean([r['bias_nls'] for r in Rm]):+.3f}")
cmd("BiasLog", f"{np.mean([r['bias_loglog'] for r in Rm]):+.3f}")
cmd("RmseNLS", f"{np.mean([r['rmse_nls'] for r in Rm]):.3f}")
cmd("RmseLog", f"{np.mean([r['rmse_loglog'] for r in Rm]):.3f}")
cmd("Coverage", pct(np.mean([r["ci_coverage"] for r in Rm]), 1))
cmd("CIWidth", f"{np.mean([r['mean_ci_width'] for r in Rm]):.2f}")
cmd("SingleClass", pct(np.mean([r["ci_single_class"] for r in Rm])))
cmd("ClassCorrectNLS", pct(np.mean([r["class_correct_nls"] for r in Rm])))
cmd("ClassCorrectLog", pct(np.mean([r["class_correct_loglog"] for r in Rm])))
cmd("MethodsAgree", pct(np.mean([r["methods_agree"] for r in Rm])))
best = [r for r in Rm if r["sigma"] == min(x["sigma"] for x in Rm)
        and r["n_points_full"] == max(x["n_points_full"] for x in Rm)]
worst = [r for r in Rm if r["sigma"] == max(x["sigma"] for x in Rm)
         and r["n_points_full"] == min(x["n_points_full"] for x in Rm)]
cmd("SingleClassBest", pct(np.mean([r["ci_single_class"] for r in best])))
cmd("SingleClassWorst", pct(np.mean([r["ci_single_class"] for r in worst])))
cmd("CIWidthBest", f"{np.mean([r['mean_ci_width'] for r in best]):.2f}")
cmd("CIWidthWorst", f"{np.mean([r['mean_ci_width'] for r in worst]):.2f}")
cmd("BestGrid", f"{max(x['n_points_full'] for x in Rm)}")
cmd("WorstGrid", f"{min(x['n_points_full'] for x in Rm)}")
cmd("SigLo", f"{min(x['sigma'] for x in Rm):.0f}")
cmd("SigHi", f"{max(x['sigma'] for x in Rm):.0f}")

cmd("RmseRatio", f"{np.mean([r['rmse_loglog'] for r in Rm])/np.mean([r['rmse_nls'] for r in Rm]):.1f}")
BOUND = {0.45, 0.95}
inter = [r for r in Rm if r["n_true"] not in BOUND]
bound = [r for r in Rm if r["n_true"] in BOUND]
cmd("ClassCorrectInterior", pct(np.mean([r["class_correct_nls"] for r in inter])))
cmd("ClassCorrectBoundary", pct(np.mean([r["class_correct_nls"] for r in bound])))
cmd("SingleClassInterior", pct(np.mean([r["ci_single_class"] for r in inter])))
cmd("SingleClassBoundary", pct(np.mean([r["ci_single_class"] for r in bound])))
cmd("InteriorNs", ", ".join(f"{v:.2f}" for v in sorted({r["n_true"] for r in inter})))
cmd("BoundaryNs", ", ".join(f"{v:.2f}" for v in sorted({r["n_true"] for r in bound})))
for npf in sorted({r["n_points_full"] for r in Rm}):
    sub = [r for r in Rm if r["n_points_full"] == npf]
    cmd(f"Cov{'Six' if npf==6 else 'Eight' if npf==8 else 'Twelve'}",
        pct(np.mean([r["ci_coverage"] for r in sub])))
    cmd(f"Kept{'Six' if npf==6 else 'Eight' if npf==8 else 'Twelve'}",
        f"{np.mean([r['mean_points_kept'] for r in sub]):.1f}")
cmd("Disagreeance", pct(1 - np.mean([r["methods_agree"] for r in Rm])))
cmd("DisagreeOneIn", f"{1/max(1e-9, 1 - np.mean([r['methods_agree'] for r in Rm])):.0f}")

rows = []
for nt in sorted({r["n_true"] for r in Rm}):
    s = [r for r in Rm if r["n_true"] == nt]
    rows.append(f"{nt:.2f} & {s[0]['true_class'].split(' (')[0]} & "
                f"{np.mean([r['bias_nls'] for r in s]):+.3f} & "
                f"{np.mean([r['bias_loglog'] for r in s]):+.3f} & "
                f"{np.mean([r['mean_ci_width'] for r in s]):.2f} & "
                f"{100*np.mean([r['ci_single_class'] for r in s]):.0f} & "
                f"{100*np.mean([r['class_correct_nls'] for r in s]):.0f} & "
                f"{100*np.mean([r['class_correct_loglog'] for r in s]):.0f}" + r" \\")
_write_table(
    os.path.join(ROOT, "paper", "table_mechanism.tex"),
    (r"& & \multicolumn{2}{c}{Bias in $\hat n$} & 95\% CI & "
     r"\multicolumn{1}{c}{CI in one} & \multicolumn{2}{c}{Correct class (\%)} \\"
     "\n" r"\cmidrule(lr){3-4}\cmidrule(lr){7-8}" "\n"
     r"$n$ & True class & NLS & LL & width & class (\%) & NLS & LL \\"),
    rows,
    "Estimation of the Peppas exponent by true value, pooled over schedules "
    "and noise. NLS: nonlinear least squares on percent released; "
    "LL: log-log linear regression. The last three columns are percentages "
    f"of profiles. {M['n_rep']} replicates and {M['n_boot']} bootstrap "
    "resamples per condition.",
    "tab:mech", "ccrrrrrr")

# ------------------------------------------------------------ experiment 4
CALP = os.path.join(RES, "bootstrap_calibration.json")
if os.path.exists(CALP):
    C = json.load(open(CALP))
    Rc = C["rows"]
    plain = [r for r in Rc if not r["rescaled"]]
    resc = [r for r in Rc if r["rescaled"]]
    cmd("calNrep", C["n_rep"]); cmd("calNboot", C["n_boot"])
    cmd("calNtrue", f"{C['n_true']:.2f}"); cmd("calSigma", f"{C['sigma']:.0f}")
    cmd("CovPlain", pct(np.mean([r["coverage"] for r in plain]), 1))
    cmd("CovResc", pct(np.mean([r["coverage"] for r in resc]), 1))
    cmd("RatioPlain", f"{np.mean([r['width_ratio'] for r in plain]):.2f}")
    cmd("RatioResc", f"{np.mean([r['width_ratio'] for r in resc]):.2f}")
    cmd("CovPlainSix", pct([r for r in plain if r["n_points_full"] == 6][0]["coverage"], 1))
    cmd("CovRescSix", pct([r for r in resc if r["n_points_full"] == 6][0]["coverage"], 1))
    cmd("CovPlainTwelve", pct([r for r in plain if r["n_points_full"] == 12][0]["coverage"], 1))
    cmd("CovRescTwelve", pct([r for r in resc if r["n_points_full"] == 12][0]["coverage"], 1))

# ------------------------------------------------------------ experiment 3
F = json.load(open(os.path.join(RES, "f2_study.json")))
Rf = F["rows"]
cmd("fNmc", f"{F['n_mc']:,}".replace(",", "\\,"))
near = [r for r in Rf if abs(r["f2_true"] - 50) < 1.0]
far = [r for r in Rf if abs(r["f2_true"] - 50) >= 1.0]
cmd("fFarAcc", pct(np.mean([r["decision_correct"] for r in far]), 1))
cmd("fFarWorst", pct(min(r["decision_correct"] for r in far), 1))
cmd("fNearAcc", pct(np.mean([r["decision_correct"] for r in near])))
ident = [r for r in Rf if r["offset"] == 0.0]
cmd("fIdentBias", f"{np.mean([r['f2_bias'] for r in ident]):.1f}")
worst_ident = min(ident, key=lambda r: r["f2_mean"])
cmd("fIdentWorst", f"{worst_ident['f2_mean']:.0f}")
cmd("fIdentWorstSD", f"{worst_ident['vessel_sd']:.0f}")
cmd("fIdentWorstN", f"{worst_ident['n_vessels']}")
nonident = [r for r in Rf if r["offset"] > 0.0]
cmd("fBiasNonIdent", f"{np.mean([r['f2_bias'] for r in nonident]):+.2f}")
W = F["worked_example"]
cmd("fWorked", f"{W['f2']:.1f}")
cmd("fWorkedLo", f"{W['ci_low']:.1f}")
cmd("fWorkedHi", f"{W['ci_high']:.1f}")
cmd("fWorkedP", pct(W["p_below_50"]))
cmd("fSDsmall", f"{[r for r in Rf if r['offset']==12.0 and r['vessel_sd']==2.0 and r['n_vessels']==12][0]['f2_sd']:.2f}")

with open(OUT, "w") as fh:
    fh.write("% generated by examples/make_report_numbers.py -- do not edit\n")
    fh.write("\n".join(lines) + "\n")
print(f"wrote {OUT} ({len(lines)} macros)")
